spring.datasource.url=jdbc:postgresql://localhost:5432/shopping_mall
spring.datasource.username=shopping_mall
spring.datasource.password=shopping_mall
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
